name: Run Rails tests using Docker Compose

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: rails-test-docker-compose.yml
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    - name: Set up the test database
      run: docker-compose run test rails db:setup
    - name: Run the Rails tests
      run: docker-compose run test
